import { lstat, mkdir, readdir, readFile, realpath, writeFile } from 'node:fs/promises';
import { join, relative, resolve, sep } from 'node:path';
import {
  KNSMOD_PACKAGE_SPEC,
  KNSMOD_TOOL,
  type KnsmodModule,
  type KnsmodPackageManifest,
} from '@kns/contracts/knsmod';
import { writeZip, pathProblem } from './zip.ts';
import { allowedMember, mediaTypeOf, sensitiveFindings } from './policy.ts';
import { publicKeyOf, sha256Hex, signManifest } from './signing.ts';
import { validatePackage, type ValidationReport } from './validate.ts';
import { loadSqlParser } from './sqlparser.ts';

async function walk(root: string, prefix = ''): Promise<string[]> {
  const out: string[] = [];
  for (const entry of await readdir(join(root, prefix), { withFileTypes: true })) {
    const name = prefix ? `${prefix}/${entry.name}` : entry.name;
    if (entry.isSymbolicLink()) throw new Error(`release input contains a symlink: ${name}`);
    if (entry.isDirectory()) out.push(...(await walk(root, name)));
    else if (entry.isFile()) out.push(name);
    else throw new Error(`release input contains a special file: ${name}`);
  }
  return out;
}

export const packageFileName = (moduleId: string, version: string) =>
  `kns-${moduleId}-${version}.knsmod`;

/** Stable manifest bytes: fixed key order, sorted entries, two-space JSON, trailing newline. */
export function manifestBytes(manifest: KnsmodPackageManifest) {
  const ordered = {
    packageSpecVersion: manifest.packageSpecVersion,
    tool: manifest.tool,
    moduleId: manifest.moduleId,
    moduleVersion: manifest.moduleVersion,
    sourceCommit: manifest.sourceCommit,
    entries: manifest.entries.map((e) => ({
      path: e.path,
      sha256: e.sha256,
      size: e.size,
      mediaType: e.mediaType,
    })),
  };
  return Buffer.from(JSON.stringify(ordered, null, 2) + '\n', 'utf8');
}

/**
 * Build a signed, deterministic .knsmod from a release directory. The same release inputs and key
 * produce byte-identical packages (Ed25519 signatures are deterministic; no timestamps are stored).
 */
export async function packModule(options: {
  input: string;
  outputDir: string;
  privateKeyPem: string;
  privateKeyPath?: string;
  keyId: string;
}): Promise<{ file: string; sha256: string; report: ValidationReport }> {
  await loadSqlParser();
  const input = await realpath(options.input);
  if (options.privateKeyPath) {
    const keyPath = await realpath(options.privateKeyPath);
    if (keyPath === input || keyPath.startsWith(input + sep))
      throw new Error('the signing key must not be inside the release input');
  }
  const names = (await walk(input)).sort((a, b) => Buffer.compare(Buffer.from(a), Buffer.from(b)));
  const problems: string[] = [];
  const members: Array<{ name: string; data: Buffer }> = [];
  for (const name of names) {
    const problem = pathProblem(name);
    if (problem) problems.push(`${name}: ${problem}`);
    else if (name === 'package-manifest.json' || name === 'signature.json')
      problems.push(`${name} is generated by the packer and must not be in the input`);
    else if (!allowedMember(name)) problems.push(`not an allowed package member: ${name}`);
    const data = await readFile(join(input, name));
    problems.push(...sensitiveFindings(name, data));
    members.push({ name, data });
  }
  if (problems.length) throw new Error(`refusing to pack:\n- ${problems.join('\n- ')}`);
  const moduleFile = members.find((m) => m.name === 'module.json');
  if (!moduleFile) throw new Error('module.json missing');
  const pkg = JSON.parse(moduleFile.data.toString('utf8')) as KnsmodModule;
  const manifest: KnsmodPackageManifest = {
    packageSpecVersion: KNSMOD_PACKAGE_SPEC,
    tool: KNSMOD_TOOL,
    moduleId: pkg.module?.id,
    moduleVersion: pkg.module?.version,
    sourceCommit: pkg.source?.commit,
    entries: members.map((m) => ({
      path: m.name,
      sha256: sha256Hex(m.data),
      size: m.data.length,
      mediaType: mediaTypeOf(m.name) ?? 'application/octet-stream',
    })),
  };
  const manifestData = manifestBytes(manifest);
  const signature = signManifest(manifestData, options.privateKeyPem, options.keyId);
  const archive = writeZip([
    ...members,
    { name: 'package-manifest.json', data: manifestData },
    {
      name: 'signature.json',
      data: Buffer.from(JSON.stringify(signature, null, 2) + '\n', 'utf8'),
    },
  ]);
  // Self-check offline with the packer's own key scoped to this module.
  const report = validatePackage(archive, {
    trustStore: {
      keys: [
        {
          keyId: options.keyId,
          publicKey: publicKeyOf(options.privateKeyPem),
          modules: [manifest.moduleId],
          revoked: false,
        },
      ],
    },
    filename: packageFileName(manifest.moduleId, manifest.moduleVersion),
  });
  if (report.status !== 'PACKAGE_VERIFIED') {
    const failed = report.stages
      .filter((s) => s.status === 'FAIL')
      .flatMap((s) => s.findings.map((f) => `${s.id}: ${f}`));
    throw new Error(`package failed self-validation:\n- ${failed.join('\n- ')}`);
  }
  const outputDir = resolve(options.outputDir);
  if (outputDir === input || outputDir.startsWith(input + sep) || relative(input, outputDir) === '')
    throw new Error('output directory must be outside the release input');
  await mkdir(outputDir, { recursive: true }); // only after the outside-the-input check above
  const file = join(outputDir, packageFileName(manifest.moduleId, manifest.moduleVersion));
  await writeFile(file, archive, { flag: 'wx' }); // immutable: never overwrite a release package
  if ((await lstat(file)).size !== archive.length) throw new Error('package write incomplete');
  return { file, sha256: sha256Hex(archive), report };
}
